### ISSUE TITLE
add deps for ssh collector

### ISSUE THREAD

**Issue by ollyg** [netdisco/netdisco-docker#12]

**Comment by inphobia** [comment]
if i'm not mistaken we need an actual openssh client since https://github.com/netdisco/netdisco/commit/d44a8f56ea25496d460fb7708dd5436dd61abcb8 due to the use of Net::OpenSSH

> In comparison, Net::OpenSSH is a pure perl module that does not have any mandatory dependencies (obviously, besides requiring OpenSSH binaries).

our docker images however contain libssh2, not the actual openssh. i guess this should be added to  https://github.com/netdisco/netdisco-docker/blob/master/netdisco-base/Dockerfile somewhere? see -> https://github.com/netdisco/netdisco-docker/pull/19#issuecomment-519618453

**Comment by rc9000** [comment]
Hi Nick! Yes that would be great, I think the Alpine package required is [openssh-client](https://pkgs.alpinelinux.org/package/edge/main/x86/openssh-client).
